### ISSUE TITLE
Delete .DS_Store files

### ISSUE THREAD

**Issue by i-walker** [arrow-kt/Category-Theory-for-Programmers.kt#43]
We may need to force push the master branch to delete the noise from the .DS_Store files. 

I will create a PR, but I may need help.

**Comment by pakoito** [comment]
Add them to the `.gitignore`

**Comment by pedrovgs** [comment]
Force push? Can't you just add ``*.DS_Store`` files to the ``.gitignore`` and run ``git rm --cached <DS_FILE>``? Then you just have to commit and push to any branch.

**Comment by i-walker** [comment]
How can I do this recrusivly. This file is in each subdir

**Comment by i-walker** [comment]
@pakoito can you review [it](https://github.com/arrow-kt/Category-Theory-for-Programmers.kt/pull/44) ?
